name: unit tests

on:
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install GLPK
        run: |
          sudo apt-get update
          sudo apt-get install -y glpk-utils

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Check if CSV files exist
        run: |
          if [ ! -f $GITHUB_WORKSPACE/tests/files/alternatives.csv ]; then
            mkdir -p $GITHUB_WORKSPACE/tests/files
            cp path/to/your/csv/files/* $GITHUB_WORKSPACE/tests/files/
          fi

      - name: Run Tests
        run: |
          python -c "import sys; sys.path.append('${GITHUB_WORKSPACE}/src'); import pytest; sys.exit(pytest.main(['tests/']))"

      - name: Check Test Results
        run: |
          if [ $? -ne 0 ]; then
            echo "Tests failed"
            exit 1
          else
            echo "Tests passed"
