name: unit tests

on:
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Run Tests
        run: |
          python -c "import sys; sys.path.append('${GITHUB_WORKSPACE}/src'); import utagms.parser; import pytest; pytest.main(['tests/'])"
